class AppString {
  static const textProvider = 'Provider';
  static const textTitle = 'Pharmacy hn clone';
  static const textSignUp = 'Sign Up';
  static const textContinueAsGuest = 'Continue as a Guest';
  static const textOr = 'or';
  static const textContinueWithFb = 'Continue with Facebook';
  static const textContinueWithGoogle = 'Continue with Google';
  static const textAlreadyHaveanAccount = 'Already have an account?';
  static const textSignIn = 'Sign In';
  static const textForgotPassword = 'Forgot Password?';
  static const textForgotPasswordMessage =
      'We will sent you a link to \n reset your password';
  static const textEnterEmailOrMobile = 'Enter email or mobile number';
  static const textSubmit = 'Submit';
  static const textLogin = 'Login';
  static const textEnterPassword = 'Enter password';
  static const textDontHaveAnAccount = 'Don’t have an account?';
  static const textRegisterNow = 'Register Now';
  static const textVerification = 'Verification';
  static const textOtpVerificationSend =
      'Please type verification code sent \n to +1 9999 999999';
  static const textRegisteration = 'Registeration';
  static const textFullName = 'Full Name';
  static const textEmailAddress = 'Email Address';
  static const textMobileNumber = 'Mobile Number';
  static const textPassword = 'Password';
  static const textConfirmPassword = 'Confirm Password';
  static const textTermsAndCondition = 'By continuing, you’re agree to our';
  static const textTermsAndCondition1 = 'Term & Condition';
  static const textAnd = 'and';
  static const textPrivacyPolicy = 'Privacy Policy.';
  static const textContinue = 'Continue';
  static const textDidntGetTheOTP = 'Didn’t get the  OTP? ';
  static const textResendOTP = 'Resend OTP';
  static const textSearchCity = 'Search City';
  static const textSearch = 'Search....';
  static const text841MontgomerySt =
      '841 Montgomery St \nJersey City, NJ 07306, USA';
  static const textJerseyCityNJ07306USA = 'Jersey City, NJ 07306, USA';
  static const textVerify = 'Verify';
  static const textAddAddressInformation = 'Add address information';
  static const textZipCodeOptional = 'Zip Code(Optional)';
  static const textThisAddressWillAppearAs = 'This address will appear as:';
  static const textHome = 'Home';
  static const textAddProducts = 'Add Products';
  static const textMyCurrentOrder = 'My Current Order';
  static const textOrderHistory = 'Order History';
  static const text3 = '3';
  static const textOffice = 'Office';
  static const textFamily = 'Family';
  static const textOther = 'Other';
  static const textSaveAndContinue = 'Save & Continue';
  static const textAllCategory = 'All Category';
  static const textMyOrder = 'My Order';
  static const textMyWishlist = 'My Wishlist';
  static const textMyProfile = 'My Profile';
  static const textNotification = 'Notification';
  static const textRewardsAndCoupons = 'Rewards & Coupons';
  static const textNewsAndBlog = 'News & Blog';
  static const textSettings = 'Settings';
  static const textLogout = 'Logout';
  static const textPharmacy = 'Pharmacy';
  static const textGrocery = 'Grocery';
  static const textVendor = 'Vendor';
  static const textDeals = 'Deals';
  static const textCategory = 'Category';
  static const textViewAllCategory = 'View All Category';
  static const textWineLiqour = 'Wine/Liqour';
  static const textVitamins = 'Vitamins';
  static const textHealth = 'Health';
  static const textSkinCare = 'Skin Care';
  static const textPopularProduct = 'Popular Product';
  static const textDoritosTangyCheeseCornChips =
      'Doritos Tangy Cheese Corn Chips';
  static const textPrice = '2.25';
  static const textViewMore = 'View more';
  static const textRecommendProduct = 'Recommend Product';
  static const textLatestNewsAndBlog = 'Latest News & Blog';
  static const textLoremIpsum =
      'Lorem Ipsum is simply dummy text\n of the printing and typesetting in…';
  static const textCategoryName = 'Category Name';
  static const text1HoursAgo = '1 hours ago';
  static const textOurInstagramFeed = 'Our Instagram Feed';
  static const textFollowUsOn = 'FOLLOW US ON';
  static const textAveenoBaby = 'Aveeno Baby';
  static const textTheOrdinaryHyaluronicAcid =
      'The Ordinary \nHyaluronic Acid 2%';
  static const textHeadAndShouldersShampoo = 'Head and Shoulders Shampoo';
  static const textTrueBasicsMultivitSport = 'TrueBasics Multivit Sport';
  static const textPondsVitaminMicellar = 'Pond’s Vitamin Micellar';
  static const textFormulaMaskCollection = 'Formula 10.0.6 Mask Collection';
  static const textBabyDiapersNewborn = 'Baby Diapers Newborn';
  static const textEarnedRewardPoints = 'Earned Reward 10 Points';
  static const text1MinAgo = '1 min ago';
  static const textOrderSuccessfullyDelivered =
      'Order 123-321-123 Successfully Delivered';
  static const text10MinAgo = '10 min ago';
  static const textOrderOutForDelivery = 'Order 123-321-123 Out for Delivery';
  static const text50MinAgo = '50 min ago';
  static const textOrderConfirmed = 'Order 123-321-123 Confirmed';
  static const text1HourAgo = '1 hour ago';
  static const textOrderSuccessfullyCancelled =
      'Order 222-546-646 Successfully Cancelled';
  static const text1DayAgo = '1 day ago';
  static const textOrderSuccessfullyReturned =
      'Order 555-555-666 Successfully Returned';
  static const text1MonthAgo = '1 month ago';
  static const textReceivedCouponOffCoupon = 'Received Coupon 10% off Coupon';
  static const text2MonthAgo = '2 month ago';
  static const textRewardPoints = 'Reward Points';
  static const textRewardPointsHistory = 'Reward Points History';
  static const textViewHistory = 'View History';
  static const text1000 = '1000';
  static const textCurrentRewardPoints = 'Current Reward Points';
  static const text100Points1Dollar = '100 Points = 1 Dollar';
  static const textCreditedOrderDetail = 'Credited from Order 123-321-123';
  static const textDebitedOrderDetail = 'Debited for Order 222-555-666';
  static const textDateAndTime = '20/03/2021 | 10:15';
  static const textBabies = 'Babies';
  static const textSnacks = 'Snacks';
  static const textDoveMen = 'Dove Men+Care Body Wash for Men’s Skin…';
  static const textStressRelief = 'Stress Relief - Eucalyptus Spearmint';
  static const textTheOrdinary = 'The Ordinary Hyaluronic Acid \$2%';
  static const textSkinCareAgeless = 'Skincare Ageless Total Repair Crème';
  static const textBathAndBody = 'Bath & Body';
  static const textCoupons = 'Coupons';
  static const textLoremIpsum2 =
      'Lorem Ipsum is simply dummy text of the and typesetting industry.';
  static const textHSDetails =
      'Head and Shoulders Shampoo, Anti Dandruff Treatment and Scalp Care, Classic Clean,32.1 fl oz, Twin Pack';
  static const textAddToWishlist = 'Add to Wishlist';
  static const textAddToCart = 'Add to Cart';
  static const textHSPrice = '\$${12.25}';
  static const textSelectQty = 'Select Qty.';
  static const textProductDetail = 'Product Detail';
  static const textLoremIpsum3 =
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.';
  static const textChatWithSeller = 'Chat With Seller';
  static const textMyCart = 'My Cart';
  static const textSubtotal = 'Subtotal (8 items):';
  static const textSubtotalAmount = '\$${60.25}';
  static const textShareMyCart = 'Share My Cart';
  static const textOrderNow = 'Order Now';
  static const textPlaceOrder = 'Place Order';

  static const text841MontgomeryStJersey =
      '841 Montgomery St, Jersey City, NJ 07306, USA';
  static const textDeliveryAddress = 'Delivery Address';
  static const textChangeAddress = 'Change Address';
  static const textBillingAddress = 'Billing Address';
  static const textBillingAddressDetail =
      '56 N 22nd St, East Orange, NJ 07017, USA';
  static const textDeliveryType = 'Delivery Type';
  static const textYourProducts = 'Your Products';
  static const textViewDetail = 'View Detail';
  static const textAddTip = 'Add Tip';
  static const textAddTipDetail = '100% of this value goes to delivery person';
  static const textAddCustom = 'Add Custom';
  static const textTip1 = '\$${1}';
  static const textTip2 = '\$${2}';
  static const textTip3 = '\$${3}';
  static const textTip4 = '\$${4}';
  static const textYourOrder = 'Your Order';
  static const textDeliveryFeesAmount = '\$${5.00}';
  static const textDeliveryFees = 'Delivery Fees';
  static const textServiceFees = 'Service Fees';
  static const textServiceFeesAmount = '\$${5.75}';
  static const textTipAmount = '\$${3.00}';
  static const textTip = 'Tip';
  static const textTotal = 'Total';
  static const textTotalAmount = '\$${73.00}';
  static const textTotalPrice = 'Total Price: \$${60.25}';
  static const textAddDiscountCoupon = 'Add Discount Coupon';
  static const textContinueToPay = 'Continue to Pay';
  static const textColgate = 'Colgate Total Whitening Toothpaste';
  static const textProductList = 'Product List';
  static const textSelectPaymentOption = 'Select Payment Option';
  static const textBankAccountsForTransfer = 'Bank accounts for Transfer';
  static const textPayusingVisaMasterCard = 'Pay using Visa/Master Card';
  static const textCashOnDelivery = 'Cash on delivery';
  static const textACHPayment = 'ACH payment';
  static const textBancoFicohsaCheckingAccountLempiras =
      'Banco Ficohsa - Checking Account Lempiras';
  static const textBankTransferID = '# 200012651887';
  static const textBancoFicohsaCheckingAccountDollar =
      'Banco Ficohsa - Checking Account Dollar ';
  static const textOrderSuccessfullyPlaced = 'Order Successfully Placed ';
  static const textViewMyOrder = 'View My Order ';
  static const textOrderNo = 'Order No: 123-321-123';
  static const textOrderNo2 = 'Order No: 235-321-546';
  static const textOrderBy = 'Order By';
  static const textEmail = 'johndoe@mail.com';
  static const textOrderDateTime = 'Order Date & Time';
  static const textOrderDateAndTime = '20/03/2021 | 10:15';
  static const textOrderDateAndTime2 = '18/03/2021 | 13:00';
  static const textCancelOrder = 'Cancel Order';
  static const textTrackOrder = 'Track Orders';
  static const textOrderPlaced = 'Order Placed';
  static const textWeHaveReceivedYourOrderOn =
      'We have received your order on 20/03/2021 | 10:15';
  static const textOrderConfirm = 'Order Confirmed';
  static const textWeHasBeenConfirmedOn =
      'We has been confirmed on 20/03/2021 | 10:20';
  static const textOrderProcessed = 'Order Processed';
  static const textWeArePreparingYourOrder = 'We are preparing your order';
  static const textReadyToShip = 'Ready To Ship';
  static const textYourOrderIsReadyForShipping =
      'Your order is ready for shipping';
  static const textDelivered = 'Delivered';
  static const textWilliamSadders = 'William Sadders';
  static const textTipText = 'Tip:';
  static const textTipTextAmount = '\$${2.00}';
  static const textDiscountAmount = '\$${-13.00}';
  static const textGrandAmount = '\$${61.00}';
  static const textOrderAmount = '\$${50.25}';
  static const textOrderAmount2 = '\$${600.25}';
  static const textDownloadInvoice = 'Download Invoice';
  static const textDiscount = 'Discount';
  static const textDiscountCode = 'Discount Code - DIS50';
  static const textRemoveCodeChangeCode = 'Remove Code | Change Code';
  static const textGrandTotal = 'Grand Total';
  static const textSelectDeliveryType = 'Select Delivery Type';
  static const textAddReason = 'Add Reason';
  static const textCancel = 'Cancel';
  static const textCustomer = 'Customer';
  static const textQty = 'Qty : ';
  static const text1 = '1';
  static const textEdit = 'Edit';
  static const textAdd = 'Add';
  static const textAddName = 'Name';
  static const textAddPrice = 'Price';
  static const textAddQty = 'Quantity';
  static const textAddImage = 'Image';
  static const textSelectCategoryType = 'Select Category Type';
}
