class AppString {
  static const textProvider = 'Provider';
  static const textTitle = 'Pharmacy hn clone';
  static const textSignUp = 'Sign Up';
  static const textContinueAsGuest = 'Continue as a Guest';
  static const textOr = 'or';
  static const textContinueWithFb = 'Continue with Facebook';
  static const textContinueWithGoogle = 'Continue with Google';
  static const textAlreadyHaveanAccount = 'Already have an account?';
  static const textSignIn = 'Sign In';
  static const textForgotPassword = 'Forgot Password?';
  static const textForgotPasswordMessage =
      'We will sent you a link to \n reset your password';
  static const textEnterEmailOrMobile = 'Enter email or mobile number';
  static const textSubmit = 'Submit';
  static const textLogin = 'Login';
  static const textEnterPassword = 'Enter password';
  static const textDontHaveAnAccount = 'Don’t have an account?';
  static const textRegisterNow = 'Register Now';
  static const textVerification = 'Verification';
  static const textOtpVerificationSend =
      'Please type verification code sent \n to +1 9999 999999';
  static const textRegisteration = 'Registeration';
  static const textFullName = 'Full Name';
  static const textEmailAddress = 'Email Address';
  static const textMobileNumber = 'Mobile Number';
  static const textPassword = 'Password';
  static const textConfirmPassword = 'Confirm Password';
  static const textTermsAndCondition = 'By continuing, you’re agree to our';
  static const textTermsAndCondition1 = 'Term & Condition';
  static const textAnd = 'and';
  static const textPrivacyPolicy = 'Privacy Policy.';
  static const textContinue = 'Continue';
  static const textDidntGetTheOTP = 'Didn’t get the  OTP? ';
  static const textResendOTP = 'Resend OTP';
  static const textSearchCity = 'Search City';
  static const textSearch = 'Search....';
  static const text841MontgomerySt =
      '841 Montgomery St \nJersey City, NJ 07306, USA';
  static const textJerseyCityNJ07306USA = 'Jersey City, NJ 07306, USA';
  static const textVerify = 'Verify';
  static const textAddAddressInformation = 'Add address information';
  static const textZipCodeOptional = 'Zip Code(Optional)';
  static const textThisAddressWillAppearAs = 'This address will appear as:';
  static const textHome = 'Home';
  static const textOffice = 'Office';
  static const textFamily = 'Family';
  static const textOther = 'Other';
  static const textSaveAndContinue = 'Save & Continue';
  static const textAllCategory = 'All Category';
  static const textMyOrder = 'My Order';
  static const textMyWishlist = 'My Wishlist';
  static const textMyProfile = 'My Profile';
  static const textNotification = 'Notification';
  static const textRewardsAndCoupons = 'Rewards & Coupons';
  static const textNewsAndBlog = 'News & Blog';
  static const textSettings = 'Settings';
  static const textPharmacy = 'Pharmacy';
  static const textDeals = 'Deals';
  static const textCategory = 'Category';
  static const textViewAllCategory = 'View All Category';
  static const textWineLiqour = 'Wine/Liqour';
  static const textVitamins = 'Vitamins';
  static const textHealth = 'Health';
  static const textSkinCare = 'Skin Care';
  static const textPopularProduct = 'Popular Product';
  static const textDoritosTangyCheeseCornChips =
      'Doritos Tangy Cheese \nCorn Chips';
  static const textPrice = '2.25';
  static const textViewMore = 'View more';
  static const textRecommendProduct = 'Recommend Product';
  static const textLatestNewsAndBlog = 'Latest News & Blog';
  static const textLoremIpsum =
      'Lorem Ipsum is simply dummy text\n of the printing and typesetting in…';
  static const textCategoryName = 'Category Name';
  static const text1HoursAgo = '1 hours ago';
  static const textOurInstagramFeed = 'Our Instagram Feed';
  static const textFollowUsOn = 'FOLLOW US ON';
  static const textAveenoBaby = 'Aveeno Baby';
  static const textTheOrdinaryHyaluronicAcid =
      'The Ordinary \nHyaluronic Acid 2%';
  static const textHeadAndShouldersShampoo = 'Head and Shoulders Shampoo';
  static const textTrueBasicsMultivitSport = 'TrueBasics Multivit Sport';
  static const textPondsVitaminMicellar = 'Pond’s Vitamin Micellar';
  static const textFormulaMaskCollection = 'Formula 10.0.6 Mask Collection';
  static const textBabyDiapersNewborn = 'Baby Diapers Newborn';
  static const textEarnedRewardPoints = 'Earned Reward 10 Points';
  static const text1MinAgo = '1 min ago';
  static const textOrderSuccessfullyDelivered =
      'Order 123-321-123 Successfully Delivered';
  static const text10MinAgo = '10 min ago';
  static const textOrderOutForDelivery = 'Order 123-321-123 Out for Delivery';
  static const text50MinAgo = '50 min ago';
  static const textOrderConfirmed = 'Order 123-321-123 Confirmed';
  static const text1HourAgo = '1 hour ago';
  static const textOrderSuccessfullyCancelled =
      'Order 222-546-646 Successfully Cancelled';
  static const text1DayAgo = '1 day ago';
  static const textOrderSuccessfullyReturned =
      'Order 555-555-666 Successfully Returned';
  static const text1MonthAgo = '1 month ago';
  static const textReceivedCouponOffCoupon = 'Received Coupon 10% off Coupon';
  static const text2MonthAgo = '2 month ago';
  static const textRewardPoints = 'Reward Points';
  static const textRewardPointsHistory = 'Reward Points History';
  static const textViewHistory = 'View History';
  static const text1000 = '1000';
  static const textCurrentRewardPoints = 'Current Reward Points';
  static const text100Points1Dollar = '100 Points = 1 Dollar';
  static const textCreditedOrderDetail = 'Credited from Order 123-321-123';
  static const textDebitedOrderDetail = 'Debited for Order 222-555-666';
  static const textDateAndTime = '20/03/2021 | 10:15';
  static const textBabies = 'Babies';
  static const textSnacks = 'Snacks';
  static const textDoveMen = 'Dove Men+Care Body Wash for Men’s Skin…';
  static const textStressRelief = 'Stress Relief - Eucalyptus Spearmint';
  static const textTheOrdinary = 'The Ordinary Hyaluronic Acid';
  static const textSkinCareAgeless = 'Skincare Ageless Total Repair Crème';
  static const textBathAndBody = 'Bath & Body';
}
